with-expecter: True
resolve-type-alias: False
issue-845-fix: True
disable-version-string: True
packages:
  github.com/viebiz/redis:
    config:
      recursive: True
      inpackage: True
      dir: "{{.InterfaceDir}}"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      filename: "mock_{{.InterfaceName}}.go"
      all: True
