// Code generated by mockery. DO NOT EDIT.

package redis

import mock "github.com/stretchr/testify/mock"

// MockHook is an autogenerated mock type for the Hook type
type MockHook struct {
	mock.Mock
}

type MockHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHook) EXPECT() *MockHook_Expecter {
	return &MockHook_Expecter{mock: &_m.Mock}
}

// DialHook provides a mock function with given fields: next
func (_m *MockHook) DialHook(next DialHook) DialHook {
	ret := _m.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for DialHook")
	}

	var r0 DialHook
	if rf, ok := ret.Get(0).(func(DialHook) DialHook); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(DialHook)
		}
	}

	return r0
}

// MockHook_DialHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DialHook'
type MockHook_DialHook_Call struct {
	*mock.Call
}

// DialHook is a helper method to define mock.On call
//   - next DialHook
func (_e *MockHook_Expecter) DialHook(next interface{}) *MockHook_DialHook_Call {
	return &MockHook_DialHook_Call{Call: _e.mock.On("DialHook", next)}
}

func (_c *MockHook_DialHook_Call) Run(run func(next DialHook)) *MockHook_DialHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(DialHook))
	})
	return _c
}

func (_c *MockHook_DialHook_Call) Return(_a0 DialHook) *MockHook_DialHook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHook_DialHook_Call) RunAndReturn(run func(DialHook) DialHook) *MockHook_DialHook_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessHook provides a mock function with given fields: next
func (_m *MockHook) ProcessHook(next ProcessHook) ProcessHook {
	ret := _m.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for ProcessHook")
	}

	var r0 ProcessHook
	if rf, ok := ret.Get(0).(func(ProcessHook) ProcessHook); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ProcessHook)
		}
	}

	return r0
}

// MockHook_ProcessHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessHook'
type MockHook_ProcessHook_Call struct {
	*mock.Call
}

// ProcessHook is a helper method to define mock.On call
//   - next ProcessHook
func (_e *MockHook_Expecter) ProcessHook(next interface{}) *MockHook_ProcessHook_Call {
	return &MockHook_ProcessHook_Call{Call: _e.mock.On("ProcessHook", next)}
}

func (_c *MockHook_ProcessHook_Call) Run(run func(next ProcessHook)) *MockHook_ProcessHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ProcessHook))
	})
	return _c
}

func (_c *MockHook_ProcessHook_Call) Return(_a0 ProcessHook) *MockHook_ProcessHook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHook_ProcessHook_Call) RunAndReturn(run func(ProcessHook) ProcessHook) *MockHook_ProcessHook_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessPipelineHook provides a mock function with given fields: next
func (_m *MockHook) ProcessPipelineHook(next ProcessPipelineHook) ProcessPipelineHook {
	ret := _m.Called(next)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPipelineHook")
	}

	var r0 ProcessPipelineHook
	if rf, ok := ret.Get(0).(func(ProcessPipelineHook) ProcessPipelineHook); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ProcessPipelineHook)
		}
	}

	return r0
}

// MockHook_ProcessPipelineHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessPipelineHook'
type MockHook_ProcessPipelineHook_Call struct {
	*mock.Call
}

// ProcessPipelineHook is a helper method to define mock.On call
//   - next ProcessPipelineHook
func (_e *MockHook_Expecter) ProcessPipelineHook(next interface{}) *MockHook_ProcessPipelineHook_Call {
	return &MockHook_ProcessPipelineHook_Call{Call: _e.mock.On("ProcessPipelineHook", next)}
}

func (_c *MockHook_ProcessPipelineHook_Call) Run(run func(next ProcessPipelineHook)) *MockHook_ProcessPipelineHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ProcessPipelineHook))
	})
	return _c
}

func (_c *MockHook_ProcessPipelineHook_Call) Return(_a0 ProcessPipelineHook) *MockHook_ProcessPipelineHook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHook_ProcessPipelineHook_Call) RunAndReturn(run func(ProcessPipelineHook) ProcessPipelineHook) *MockHook_ProcessPipelineHook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHook creates a new instance of MockHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHook {
	mock := &MockHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
