// Code generated by mockery. DO NOT EDIT.

package redis

import (
	context "context"
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// MockDialHook is an autogenerated mock type for the DialHook type
type MockDialHook struct {
	mock.Mock
}

type MockDialHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDialHook) EXPECT() *MockDialHook_Expecter {
	return &MockDialHook_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, network, addr
func (_m *MockDialHook) Execute(ctx context.Context, network string, addr string) (net.Conn, error) {
	ret := _m.Called(ctx, network, addr)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 net.Conn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (net.Conn, error)); ok {
		return rf(ctx, network, addr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) net.Conn); ok {
		r0 = rf(ctx, network, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, network, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDialHook_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDialHook_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - addr string
func (_e *MockDialHook_Expecter) Execute(ctx interface{}, network interface{}, addr interface{}) *MockDialHook_Execute_Call {
	return &MockDialHook_Execute_Call{Call: _e.mock.On("Execute", ctx, network, addr)}
}

func (_c *MockDialHook_Execute_Call) Run(run func(ctx context.Context, network string, addr string)) *MockDialHook_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDialHook_Execute_Call) Return(_a0 net.Conn, _a1 error) *MockDialHook_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDialHook_Execute_Call) RunAndReturn(run func(context.Context, string, string) (net.Conn, error)) *MockDialHook_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDialHook creates a new instance of MockDialHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDialHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDialHook {
	mock := &MockDialHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
