// Code generated by mockery. DO NOT EDIT.

package redis

import mock "github.com/stretchr/testify/mock"

// MockConsistentHash is an autogenerated mock type for the ConsistentHash type
type MockConsistentHash struct {
	mock.Mock
}

type MockConsistentHash_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsistentHash) EXPECT() *MockConsistentHash_Expecter {
	return &MockConsistentHash_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: _a0
func (_m *MockConsistentHash) Get(_a0 string) string {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConsistentHash_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConsistentHash_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 string
func (_e *MockConsistentHash_Expecter) Get(_a0 interface{}) *MockConsistentHash_Get_Call {
	return &MockConsistentHash_Get_Call{Call: _e.mock.On("Get", _a0)}
}

func (_c *MockConsistentHash_Get_Call) Run(run func(_a0 string)) *MockConsistentHash_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConsistentHash_Get_Call) Return(_a0 string) *MockConsistentHash_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsistentHash_Get_Call) RunAndReturn(run func(string) string) *MockConsistentHash_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsistentHash creates a new instance of MockConsistentHash. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsistentHash(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsistentHash {
	mock := &MockConsistentHash{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
