// Code generated by mockery. DO NOT EDIT.

package hscan

import (
	reflect "reflect"

	mock "github.com/stretchr/testify/mock"
)

// MockdecoderFunc is an autogenerated mock type for the decoderFunc type
type MockdecoderFunc struct {
	mock.Mock
}

type MockdecoderFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdecoderFunc) EXPECT() *MockdecoderFunc_Expecter {
	return &MockdecoderFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *MockdecoderFunc) Execute(_a0 reflect.Value, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(reflect.Value, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockdecoderFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockdecoderFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 reflect.Value
//   - _a1 string
func (_e *MockdecoderFunc_Expecter) Execute(_a0 interface{}, _a1 interface{}) *MockdecoderFunc_Execute_Call {
	return &MockdecoderFunc_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *MockdecoderFunc_Execute_Call) Run(run func(_a0 reflect.Value, _a1 string)) *MockdecoderFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(reflect.Value), args[1].(string))
	})
	return _c
}

func (_c *MockdecoderFunc_Execute_Call) Return(_a0 error) *MockdecoderFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockdecoderFunc_Execute_Call) RunAndReturn(run func(reflect.Value, string) error) *MockdecoderFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockdecoderFunc creates a new instance of MockdecoderFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdecoderFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdecoderFunc {
	mock := &MockdecoderFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
